version: "3.9"

services:
  db:
    image: mongo
    container_name: gl-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    ports: 
      - 27017-27019:27017-27019
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./data/db:/data/db
  frontend:
    build: ./grocery-list-frontend
    container_name: gl-frontend
    ports: 
      - 80:80
    hostname: 0.0.0.0
  backend:
    build: ./grocery-list-backend
    container_name: gl-backend
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - MONGODB_DATABASE=${DB_NAME}
      - MONGODB_USERNAME=${DB_USER}
      - MONGODB_PASSWORD=${DB_PASSWORD}
      - MONGODB_HOSTNAME=mongodb
    ports:
      - 5000:5000
    depends_on:
      - db