version: "3.9"

services:
  db:
    image: mongo
    container_name: gl-db
    environment:
      - MONGO_INITDB_DATABASE=default_db
      - MONGO_INITDB_ROOT_USERNAME=default_user
      - MONGO_INITDB_ROOT_PASSWORD=default_password
    ports: 
      - 27017-27019:27017-27019
  frontend:
    build: ./grocery-list-frontend
    container_name: gl-frontend
    ports: 
      - 80:80
    hostname: 0.0.0.0
  backend:
    build: ./grocery-list-backend
    container_name: gl-backend
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - MONGODB_DATABASE=default_db
      - MONGODB_USERNAME=default_user
      - MONGODB_PASSWORD=default_password
      - MONGODB_HOSTNAME=mongodb
    ports:
      - 5000:5000
    depends_on:
      - db